const products = [
  {
    id: 'rec43w3ipXvP28vog',
    title: 'comfy sofa chair',
    company: 'ikea',
    image: 'images/yellow-chair.jpg',
    price: '9,000',
  },
  {
    id: 'rec4f2RIftFCb7aHh',
    title: 'marlin couch',
    company: 'castlery',
    image: 'images/blue-couch.jpg',
    price: '19,999',
  },
  {
    id: 'rec8kkCmSiMkbkiko',
    title: 'dusky sofa set',
    company: 'ashley',
    image: 'images/gray-sofa-set.jpg',
    price: '25,999',
  },
  {
    id: 'recBohCqQsot4Q4II',
    title: "king's bed",
    company: 'ashley',
    image: 'images/gray-bed.jpg',
    price: '40,000',
  },
  {
    id: 'recDG1JRZnbpRHpoy',
    title: 'marble dining table',
    company: 'ashley',
    image: 'images/circular-dining-table.jpg',
    price: '34,550',
  },
  {
    id: 'recNWGyP7kjFhSqw3',
    title: 'princess bed',
    company: 'bernhardt',
    image: 'images/kids-bed.jpg',
    price: '20,000',
  },
  {
    id: 'recZEougL5bbY4AEx',
    title: 'bedside wooden cabinet',
    company: 'castlery',
    image: 'images/bedside-wooden-cabinet.jpg',
    price: '6,999',
  },
  {
    id: 'recjMK1jgTb2ld7sv',
    title: 'Organic Dining table',
    company: 'bernhardt',
    image: 'images/wooden-dining-table.jpg',
    price: '22,000',
  },
  {
    id: 'recmg2a1ctaEJNZhu',
    title: 'royal sofa set',
    company: 'castlery',
    image: 'images/green-sofa-set.jpg',
    price: '31,000',
  },
  {
    id: 'recvKMNR3YFw0bEt3',
    title: 'single bookshelf',
    company: 'bernhardt',
    image: 'images/white-bookshelf.jpg',
    price: '12,000',
  },
  {
    id: 'recxaXFy5IW539sgM',
    title: 'wallside bookshelf',
    company: 'ikea',
    image: 'images/big-white-bookshelf.jpg',
    price: '34,999',
  },
  {
    id: 'recyqtRglGNGtO4Q5',
    title: 'bedside drawer',
    company: 'bernhardt',
    image: 'images/bedside-drawer.jpg',
    price: '4,999',
  },
];
